name: CDK Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: cdk
        run: npm install

      - name: Install CDK
        working-directory: cdk
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your preferred region

      - name: CDK Bootstrap
        working-directory: cdk
        run: cdk bootstrap
      
      - name: CDK Synth
        working-directory: cdk
        run: cdk synth

      - name: CDK Deploy
        if: github.event_name == 'push'
        working-directory: cdk
        run: cdk deploy --all --require-approval never
