name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push register app
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          file: ./server/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tunedinbackend:latest
